//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Thor.Net.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class JörðEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new JörðEntities object using the connection string found in the 'JörðEntities' section of the application configuration file.
        /// </summary>
        public JörðEntities() : base("name=JörðEntities", "JörðEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JörðEntities object.
        /// </summary>
        public JörðEntities(string connectionString) : base(connectionString, "JörðEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new JörðEntities object.
        /// </summary>
        public JörðEntities(EntityConnection connection) : base(connection, "JörðEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FoundryApplication> FoundryApplications
        {
            get
            {
                if ((_FoundryApplications == null))
                {
                    _FoundryApplications = base.CreateObjectSet<FoundryApplication>("FoundryApplications");
                }
                return _FoundryApplications;
            }
        }
        private ObjectSet<FoundryApplication> _FoundryApplications;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FoundryTarget> FoundryTargets
        {
            get
            {
                if ((_FoundryTargets == null))
                {
                    _FoundryTargets = base.CreateObjectSet<FoundryTarget>("FoundryTargets");
                }
                return _FoundryTargets;
            }
        }
        private ObjectSet<FoundryTarget> _FoundryTargets;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FoundryApplications EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoundryApplications(FoundryApplication foundryApplication)
        {
            base.AddObject("FoundryApplications", foundryApplication);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FoundryTargets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoundryTargets(FoundryTarget foundryTarget)
        {
            base.AddObject("FoundryTargets", foundryTarget);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JörðModel", Name="FoundryApplication")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FoundryApplication : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FoundryApplication object.
        /// </summary>
        /// <param name="uri">Initial value of the Uri property.</param>
        public static FoundryApplication CreateFoundryApplication(global::System.String uri)
        {
            FoundryApplication foundryApplication = new FoundryApplication();
            foundryApplication.Uri = uri;
            return foundryApplication;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Uri
        {
            get
            {
                return _Uri;
            }
            set
            {
                if (_Uri != value)
                {
                    OnUriChanging(value);
                    ReportPropertyChanging("Uri");
                    _Uri = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Uri");
                    OnUriChanged();
                }
            }
        }
        private global::System.String _Uri;
        partial void OnUriChanging(global::System.String value);
        partial void OnUriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TargetUri
        {
            get
            {
                return _TargetUri;
            }
            set
            {
                OnTargetUriChanging(value);
                ReportPropertyChanging("TargetUri");
                _TargetUri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TargetUri");
                OnTargetUriChanged();
            }
        }
        private global::System.String _TargetUri;
        partial void OnTargetUriChanging(global::System.String value);
        partial void OnTargetUriChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JörðModel", Name="FoundryTarget")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FoundryTarget : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FoundryTarget object.
        /// </summary>
        /// <param name="uri">Initial value of the Uri property.</param>
        public static FoundryTarget CreateFoundryTarget(global::System.String uri)
        {
            FoundryTarget foundryTarget = new FoundryTarget();
            foundryTarget.Uri = uri;
            return foundryTarget;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Uri
        {
            get
            {
                return _Uri;
            }
            set
            {
                if (_Uri != value)
                {
                    OnUriChanging(value);
                    ReportPropertyChanging("Uri");
                    _Uri = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Uri");
                    OnUriChanged();
                }
            }
        }
        private global::System.String _Uri;
        partial void OnUriChanging(global::System.String value);
        partial void OnUriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
    }

    #endregion
    
}
