//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thor.Net.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Foundry {
            get {
                return ((string)(this["Foundry"]));
            }
            set {
                this["Foundry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Thor.Models.Jord.FoundryTarget FoundryActiveTarget {
            get {
                return ((global::Thor.Models.Jord.FoundryTarget)(this["FoundryActiveTarget"]));
            }
            set {
                this["FoundryActiveTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Thor.Models.Jord.FoundryApplication FoundryActiveApplication {
            get {
                return ((global::Thor.Models.Jord.FoundryApplication)(this["FoundryActiveApplication"]));
            }
            set {
                this["FoundryActiveApplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Thor.Models.Jord.FoundryDeployment FoundryActiveDeployment {
            get {
                return ((global::Thor.Models.Jord.FoundryDeployment)(this["FoundryActiveDeployment"]));
            }
            set {
                this["FoundryActiveDeployment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Thor.Models.Jord.FoundryService FoundryActiveService {
            get {
                return ((global::Thor.Models.Jord.FoundryService)(this["FoundryActiveService"]));
            }
            set {
                this["FoundryActiveService"] = value;
            }
        }
    }
}
